name: GitHub Pages
on:
    push:
        branches:
            - nextjs_setup
            - master

permissions:
    pages: write
    id-token: write

jobs:
    deploy:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: Build
              run: script/build.sh
            - uses: actions/upload-artifact@v3
              with:
                  path: ./docs
                  retention-days: 1
            - uses: actions/deploy-pages@v1
